In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
a=np.array([1, 2, 3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [ ]:
import numpy as np
dt=np.dtype(np.int32)
print(dt)

int32


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
import numpy as np 
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
import numpy as np
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [ ]:
x = np.ones([2,2], dtype=int)
print(x)

[[1 1]
 [1 1]]


In [ ]:
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [ ]:
# s = 'Hello World'
# a = np.frombuffer(s, dtype='S1')
# print(a)

In [ ]:
list = range(5)
print(list)

range(0, 5)


In [ ]:
list = range(5)
it = iter(list)
# use iterator to create ndarray
x = np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [ ]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [ ]:
# dtype set
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]
